version: '3.8'
services:
  fl-aggregator-service:
    container_name: fl_aggregator_service
    restart: always
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    networks:
      - app-network
    image: fl_aggregator_service
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/www/fl-aggregator-service
    ports:
      - "7200:7200"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7200" ]
      interval: 15s
      timeout: 10s
      retries: 5


networks:
  app-network:
    external: true